/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Booking;
import Models.BookingLine;
import Models.Customer;
import Models.DBManager;
import Models.ExcelWriter;
import Models.LoggedInUser;
import Models.Staff;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;

/**
 *
 * @author Paul
 */
public class StaffHome extends javax.swing.JFrame {
    //user details to be passed in
    private LoggedInUser loggedInUser = new LoggedInUser();

    /**
     * home screen for staff to view bookings, rooms customers, and create reports
     */
    public StaffHome(LoggedInUser loggedInUser) {
        this.loggedInUser = loggedInUser;
        loadFrame();
    }
    
    //load initial components into frame
    public void loadFrame()
    {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Font ttfBase = null;
        Font ttfReal = null;
        try 
        {
            InputStream myStream = new BufferedInputStream(new FileInputStream("src/fonts/Dillanda Caligraphy Script Demo.ttf"));
            ttfBase = Font.createFont(Font.TRUETYPE_FONT, myStream);
            ttfReal = ttfBase.deriveFont(Font.BOLD, 50);
            lblTitle.setFont(ttfReal);
            lblTitle.setForeground(new Color(102, 0, 0));

        } catch (Exception ex) 
        {
            ex.printStackTrace();
            System.err.println("Custom font not loaded.");
        }       
        btnSignIn.setText("Logged in as " + loggedInUser.getUsername());
        btnSignIn.setEnabled(false);
        btnStaffViewStaff.setVisible(false);
        btnStaffViewRooms.setVisible(false);
        btnStaffReports.setVisible(false);
        
        if(loggedInUser.getStaffTypeID() == 2 || loggedInUser.getStaffTypeID() == 3)
        {
            btnStaffViewStaff.setVisible(true);
            btnStaffReports.setVisible(true);
        }
        if(loggedInUser.getStaffTypeID() == 2)
        {
            btnStaffViewRooms.setVisible(true);
        }
        
        btnRegister.setText("Logout");
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframeStaffChangePassword = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnSubmitPassword = new javax.swing.JButton();
        btnClosePassword = new javax.swing.JButton();
        jframeEditStaffDetails = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsernameStaff = new javax.swing.JTextField();
        txtFirstNameStaff = new javax.swing.JTextField();
        txtLastNameStaff = new javax.swing.JTextField();
        txtEmailStaff = new javax.swing.JTextField();
        btnEditSubmit = new javax.swing.JButton();
        btnEditClear = new javax.swing.JButton();
        btnEditClose = new javax.swing.JButton();
        jframeStaffReports = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jdateDateFrom = new com.toedter.calendar.JDateChooser();
        jdateDateUntil = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStaffBookingReport = new javax.swing.JButton();
        btnStaffIncomeReport = new javax.swing.JButton();
        btnStaffClose = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAbout = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnSignIn = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        btnControlPanel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnStaffEditDetails = new javax.swing.JButton();
        btnStaffChangePassword = new javax.swing.JButton();
        btnNewBooking = new javax.swing.JButton();
        lblStaff = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnStaffViewBookings = new javax.swing.JButton();
        btnStaffViewCustomers = new javax.swing.JButton();
        btnStaffViewRooms = new javax.swing.JButton();
        btnStaffViewStaff = new javax.swing.JButton();
        btnStaffReports = new javax.swing.JButton();
        btnTrunc = new javax.swing.JButton();

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Change Password");

        txtUsername1.setEditable(false);
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Username");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Password");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Confirm Password");

        btnSubmitPassword.setText("Submit");
        btnSubmitPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitPasswordActionPerformed(evt);
            }
        });

        btnClosePassword.setText("Close");
        btnClosePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframeStaffChangePasswordLayout = new javax.swing.GroupLayout(jframeStaffChangePassword.getContentPane());
        jframeStaffChangePassword.getContentPane().setLayout(jframeStaffChangePasswordLayout);
        jframeStaffChangePasswordLayout.setHorizontalGroup(
            jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeStaffChangePasswordLayout.createSequentialGroup()
                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jframeStaffChangePasswordLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel14))
                    .addGroup(jframeStaffChangePasswordLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jframeStaffChangePasswordLayout.createSequentialGroup()
                                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtConfirmPassword)
                                    .addComponent(txtPassword)
                                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jframeStaffChangePasswordLayout.createSequentialGroup()
                                .addComponent(btnSubmitPassword)
                                .addGap(30, 30, 30)
                                .addComponent(btnClosePassword)
                                .addGap(27, 27, 27)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jframeStaffChangePasswordLayout.setVerticalGroup(
            jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframeStaffChangePasswordLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jframeStaffChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitPassword)
                    .addComponent(btnClosePassword))
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Staff Details");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("First Name");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Last Name");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email");

        btnEditSubmit.setText("Submit");
        btnEditSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSubmitActionPerformed(evt);
            }
        });

        btnEditClear.setText("Clear");
        btnEditClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClearActionPerformed(evt);
            }
        });

        btnEditClose.setText("Close");
        btnEditClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframeEditStaffDetailsLayout = new javax.swing.GroupLayout(jframeEditStaffDetails.getContentPane());
        jframeEditStaffDetails.getContentPane().setLayout(jframeEditStaffDetailsLayout);
        jframeEditStaffDetailsLayout.setHorizontalGroup(
            jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeEditStaffDetailsLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframeEditStaffDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtFirstNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframeEditStaffDetailsLayout.createSequentialGroup()
                        .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jframeEditStaffDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)))
                        .addGap(18, 18, 18)
                        .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsernameStaff)
                            .addComponent(txtLastNameStaff)
                            .addComponent(txtEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframeEditStaffDetailsLayout.createSequentialGroup()
                        .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jframeEditStaffDetailsLayout.createSequentialGroup()
                                .addComponent(btnEditSubmit)
                                .addGap(33, 33, 33)
                                .addComponent(btnEditClear)
                                .addGap(35, 35, 35)
                                .addComponent(btnEditClose))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jframeEditStaffDetailsLayout.setVerticalGroup(
            jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeEditStaffDetailsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsernameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFirstNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLastNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jframeEditStaffDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSubmit)
                    .addComponent(btnEditClear)
                    .addComponent(btnEditClose))
                .addGap(38, 38, 38))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Export Reports");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("From");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Until");

        btnStaffBookingReport.setText("Export Booking Report");
        btnStaffBookingReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffBookingReportActionPerformed(evt);
            }
        });

        btnStaffIncomeReport.setText("Export Income Report");
        btnStaffIncomeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffIncomeReportActionPerformed(evt);
            }
        });

        btnStaffClose.setText("Close");

        javax.swing.GroupLayout jframeStaffReportsLayout = new javax.swing.GroupLayout(jframeStaffReports.getContentPane());
        jframeStaffReports.getContentPane().setLayout(jframeStaffReportsLayout);
        jframeStaffReportsLayout.setHorizontalGroup(
            jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframeStaffReportsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                                .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdateDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnStaffBookingReport))
                                .addGap(35, 35, 35)
                                .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jdateDateUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnStaffIncomeReport)))))
                    .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnStaffClose)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jframeStaffReportsLayout.setVerticalGroup(
            jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeStaffReportsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdateDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdateDateUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(jframeStaffReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStaffBookingReport)
                    .addComponent(btnStaffIncomeReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnStaffClose)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Drovers Lodge");

        jPanel2.setBackground(new java.awt.Color(224, 224, 224));
        jPanel2.setToolTipText("");

        btnAbout.setText("About Drovers Lodge");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnCart.setBackground(new java.awt.Color(51, 0, 0));
        btnCart.setForeground(new java.awt.Color(255, 255, 255));
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basket.png"))); // NOI18N
        btnCart.setText("Cart");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        btnControlPanel.setBackground(new java.awt.Color(51, 0, 0));
        btnControlPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnControlPanel.setText("Control Panel");
        btnControlPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAbout)
                .addGap(18, 18, 18)
                .addComponent(btnControlPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignIn)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnCart)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbout)
                    .addComponent(btnSignIn)
                    .addComponent(btnRegister)
                    .addComponent(btnCart)
                    .addComponent(btnControlPanel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnStaffEditDetails.setText("Edit Details");
        btnStaffEditDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffEditDetailsActionPerformed(evt);
            }
        });

        btnStaffChangePassword.setText("Change Password");
        btnStaffChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffChangePasswordActionPerformed(evt);
            }
        });

        btnNewBooking.setText("Make New Booking");
        btnNewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewBooking)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnStaffEditDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStaffChangePassword, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnStaffEditDetails)
                .addGap(34, 34, 34)
                .addComponent(btnStaffChangePassword)
                .addGap(31, 31, 31)
                .addComponent(btnNewBooking)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblStaff.setBackground(new java.awt.Color(255, 255, 51));
        lblStaff.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStaff.setForeground(new java.awt.Color(51, 51, 51));
        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaff.setText("STAFF");
        lblStaff.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnStaffViewBookings.setText("View Bookings");
        btnStaffViewBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffViewBookingsActionPerformed(evt);
            }
        });

        btnStaffViewCustomers.setText("View Customers");
        btnStaffViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffViewCustomersActionPerformed(evt);
            }
        });

        btnStaffViewRooms.setText("View Rooms");
        btnStaffViewRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffViewRoomsActionPerformed(evt);
            }
        });

        btnStaffViewStaff.setText("View Staff");
        btnStaffViewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffViewStaffActionPerformed(evt);
            }
        });

        btnStaffReports.setText("Reports");
        btnStaffReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStaffViewBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffViewCustomers))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStaffViewStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffViewRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnStaffReports, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStaffViewBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffViewStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffReports, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStaffViewRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffViewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnTrunc.setText("trunc");
        btnTrunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTrunc)
                        .addGap(108, 108, 108)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStaff)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnTrunc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        loggedInUser = new LoggedInUser();
        loggedInUser.setIsLoggedIn(false);
        btnSignIn.setText("Sign In");
        btnSignIn.setEnabled(true);
        btnRegister.setText("Register");
        MainMenu rForm = new MainMenu();
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        Cart rForm = new Cart(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnStaffEditDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffEditDetailsActionPerformed
        jframeEditStaffDetails.setVisible(true);
        jframeEditStaffDetails.setSize(440,400);
        jframeEditStaffDetails.getContentPane().setBackground(Color.white);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        jframeEditStaffDetails.setLocation(dim.width/2-jframeEditStaffDetails.getSize().width/2, dim.height/2-jframeEditStaffDetails.getSize().height/2);
        
        loadStaffDetails();
    }//GEN-LAST:event_btnStaffEditDetailsActionPerformed
    
    public void loadStaffDetails()
    {
        DBManager db = new DBManager();
        Staff loggedInStaff = new Staff();
        loggedInStaff = db.getStaffFromUsername(loggedInUser.getUsername());
        
        String username = loggedInStaff.getUsername();
        String firstName = loggedInStaff.getFirstName();
        String lastName = loggedInStaff.getLastName();
        String email = loggedInStaff.getEmail();
        
        txtUsernameStaff.setText(username);
        txtUsernameStaff.setEnabled(false);
        txtFirstNameStaff.setText(firstName);
        txtLastNameStaff.setText(lastName);
        txtEmailStaff.setText(email);
    }
    
    private void btnStaffChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffChangePasswordActionPerformed
        jframeStaffChangePassword.setVisible(true);
        jframeStaffChangePassword.setSize(400,400);
        jframeStaffChangePassword.getContentPane().setBackground(Color.white);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        jframeStaffChangePassword.setLocation(dim.width/2-jframeStaffChangePassword.getSize().width/2, dim.height/2-jframeStaffChangePassword.getSize().height/2);
        jframeStaffChangePassword.setVisible(true);

        txtUsername1.setText(loggedInUser.getUsername());
        txtUsername1.setEnabled(false);
    }//GEN-LAST:event_btnStaffChangePasswordActionPerformed

    private void btnNewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookingActionPerformed
        CheckAvailability rForm = new CheckAvailability(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnNewBookingActionPerformed

    private void btnStaffViewBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffViewBookingsActionPerformed
    StaffViewBookings rForm = new StaffViewBookings(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnStaffViewBookingsActionPerformed

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void btnSubmitPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitPasswordActionPerformed
        DBManager db = new DBManager();
        String newPassword = "";
        int staffID = db.getStaffFromUsername(loggedInUser.getUsername()).getStaffID();
        if(txtPassword.getText().isEmpty() || txtConfirmPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in all password fields");
        }
        else
        {
            if(!txtPassword.getText().equals(txtConfirmPassword.getText()))
            {
                JOptionPane.showMessageDialog(null, "Passwords don't match");
            }
            else
            {
                //update password in db if correct
                newPassword = txtPassword.getText();
            }            
        }
        db.updateStaffPassword(staffID, newPassword);
        JOptionPane.showMessageDialog(null, "Password changed");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
        jframeStaffChangePassword.dispose();
    }//GEN-LAST:event_btnSubmitPasswordActionPerformed

    private void btnClosePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosePasswordActionPerformed
        jframeStaffChangePassword.dispose();
    }//GEN-LAST:event_btnClosePasswordActionPerformed

    private void btnEditSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSubmitActionPerformed
        if(txtUsernameStaff.getText().isEmpty() ||   txtFirstNameStaff.getText().isEmpty() ||
               txtLastNameStaff.getText().isEmpty() || txtEmailStaff.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in all fields");
        }
        else
        {
            DBManager db = new DBManager();
            Staff loggedInStaff = new Staff();
            loggedInStaff = db.getStaffFromUsername(loggedInUser.getUsername());
            int staffID = loggedInStaff.getStaffID();

            String firstName = txtFirstNameStaff.getText();
            String lastName = txtLastNameStaff.getText();
            String email = txtEmailStaff.getText();

            Staff updateStaffDetails = new Staff(firstName, lastName, email);
            db.updateStaffDetails(staffID, updateStaffDetails);      
            JOptionPane.showMessageDialog(null, "Details updated");
            jframeEditStaffDetails.dispose();
        }
    }//GEN-LAST:event_btnEditSubmitActionPerformed

    private void btnEditClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClearActionPerformed
        loadStaffDetails();
    }//GEN-LAST:event_btnEditClearActionPerformed

    private void btnEditCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCloseActionPerformed
        jframeEditStaffDetails.dispose();
    }//GEN-LAST:event_btnEditCloseActionPerformed

    private void btnControlPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPanelActionPerformed
        if(loggedInUser.getUserTypeID() == 2)
        {
            CustomerHome rForm = new CustomerHome(loggedInUser);
            this.dispose();
            rForm.setVisible(true);
        } else if(loggedInUser.getUserTypeID() == 3)
        {
            StaffHome rForm = new StaffHome(loggedInUser);
            this.dispose();
            rForm.setVisible(true);
        }
    }//GEN-LAST:event_btnControlPanelActionPerformed

    private void btnStaffViewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffViewStaffActionPerformed
        StaffViewStaff rForm = new StaffViewStaff(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnStaffViewStaffActionPerformed

    private void btnStaffViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffViewCustomersActionPerformed
        StaffViewCustomers rForm = new StaffViewCustomers(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnStaffViewCustomersActionPerformed

    private void btnStaffViewRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffViewRoomsActionPerformed
        StaffViewRooms rForm = new StaffViewRooms(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnStaffViewRoomsActionPerformed

    private void btnTruncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruncActionPerformed
        DBManager db = new DBManager();
        db.truncBookingsBookLinesPayments();
    }//GEN-LAST:event_btnTruncActionPerformed

    private void btnStaffBookingReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffBookingReportActionPerformed
        Date dateFrom = jdateDateFrom.getDate();
        Date dateUntil = jdateDateUntil.getDate();
        HashMap<Integer, BookingLine> bookingLines = new HashMap<Integer, BookingLine>();
        DBManager db = new DBManager();
        bookingLines = db.getBookingLinesBetweenDates(dateFrom, dateUntil);  
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");       
        SimpleDateFormat fileFormat = new SimpleDateFormat("dd_MM_yyyy");
        String strDateFrom = fileFormat.format(dateFrom);
        String strDateUntil = fileFormat.format(dateUntil);
        String strAvailability = strDateFrom + "_until_" + strDateUntil;   
        Date today = new Date();
        String todaysDate = fileFormat.format(today);   
        //load table on the fly with booking details for report        
        String colNames[] = {"Booking ID", "RoomID", "Check In", "Check Out", "Customer ID"};
        Object[][] tableData = new Object[bookingLines.keySet().size()][5];
        int index = 0;
        for (Integer key : bookingLines.keySet())
        {
            BookingLine currentBookingLine = bookingLines.get(key);
            tableData[index][0] = currentBookingLine.getBookingID();
            tableData[index][1] = currentBookingLine.getRoomID();
            tableData[index][2] = dateFormat.format(currentBookingLine.getCheckInDate());
            tableData[index][3] = dateFormat.format(currentBookingLine.getCheckOutDate());
            tableData[index][4] = db.getBookingFromBookingID(currentBookingLine.getBookingID()).getCustomerID();
            index++;
        }
        DefaultTableModel dtm = new DefaultTableModel(tableData,colNames);
        JTable tblBookingReport = new JTable(dtm);
        //create excel sheet showing booking report table
        ExcelWriter export = new ExcelWriter();
                
        export.newExcelFile(strAvailability + "_" + todaysDate);
        File file = new File("src\\reports\\Availability\\Availability_Report_" + strAvailability + "_" + todaysDate + ".xls");
       
        try
        {
            export.getExcelBookingData(tblBookingReport, file);
        }
        catch (IOException ex)
        {
            Logger.getLogger(StaffViewBookings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnStaffBookingReportActionPerformed

    private void btnStaffIncomeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffIncomeReportActionPerformed
        Date dateFrom = jdateDateFrom.getDate();
        Date dateUntil = jdateDateUntil.getDate();
        HashMap<Integer, Booking> bookings = new HashMap<Integer, Booking>();
        DBManager db = new DBManager();
        bookings = db.getBookingsBetweenDates(dateFrom, dateUntil);     
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");       
        SimpleDateFormat fileFormat = new SimpleDateFormat("dd_MM_yyyy");
        String strDateFrom = fileFormat.format(dateFrom);
        String strDateUntil = fileFormat.format(dateUntil);
        String strAvailability = strDateFrom + "_until_" + strDateUntil;   
        Date today = new Date();
        String todaysDate = fileFormat.format(today);
        double totalCost = 0;
        double totalOutstanding = 0;
        
        String colNames[] = {"Booking ID", "Date Booked", "Outstanding Balance", "Total Cost", "Payment Type", "Customer Name"};
        Object[][] tableData = new Object[(bookings.keySet().size())+1][6];
        int index = 0;
        for (Integer key : bookings.keySet())
        {
            Booking currentBooking = bookings.get(key);
            tableData[index][0] = currentBooking.getBookingID();
            tableData[index][1] = dateFormat.format(currentBooking.getDateBooked());
            tableData[index][2] = currentBooking.getOutstandingBalance();
            totalOutstanding = totalOutstanding + currentBooking.getOutstandingBalance();
            tableData[index][3] = currentBooking.getTotalCost();
            totalCost = totalCost + currentBooking.getTotalCost();
            tableData[index][4] = db.getPaymentTypeFromPaymentTypeID(currentBooking.getPaymentTypeID());
            Customer customer = db.getCustomerFromCustomerID(currentBooking.getCustomerID());
            String customerName = customer.getFirstName() + " " + customer.getLastName();
            tableData[index][5] = customerName;
            index++;
        }
        tableData[index][0] = "";
        tableData[index][1] = "";
        tableData[index][2] = totalOutstanding;
        tableData[index][3] = totalCost;
        tableData[index][4] = "";
        tableData[index][5] = "";
        DefaultTableModel dtm = new DefaultTableModel(tableData,colNames);
        JTable tblBookingReport = new JTable(dtm);
    
        ExcelWriter export = new ExcelWriter();
                
        export.newExcelFile(strAvailability + "_" + todaysDate);
        File file = new File("src\\reports\\Income\\Income_Report_" + strAvailability + "_" + todaysDate + ".xls");
       
        try
        {
            export.getExcelBookingData(tblBookingReport, file);
        }
        catch (IOException ex)
        {
            Logger.getLogger(StaffViewBookings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStaffIncomeReportActionPerformed

    private void btnStaffReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffReportsActionPerformed
        jframeStaffReports.setVisible(true);
        jframeStaffReports.setSize(640,400); 
        jframeStaffReports.getContentPane().setBackground(Color.white); 
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        jframeStaffReports.setLocation(dim.width/2-jframeStaffReports.getSize().width/2, dim.height/2-jframeStaffReports.getSize().height/2);
    }//GEN-LAST:event_btnStaffReportsActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        About rForm = new About(loggedInUser);
        this.dispose();
        rForm.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StaffHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnClosePassword;
    private javax.swing.JButton btnControlPanel;
    private javax.swing.JButton btnEditClear;
    private javax.swing.JButton btnEditClose;
    private javax.swing.JButton btnEditSubmit;
    private javax.swing.JButton btnNewBooking;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnStaffBookingReport;
    private javax.swing.JButton btnStaffChangePassword;
    private javax.swing.JButton btnStaffClose;
    private javax.swing.JButton btnStaffEditDetails;
    private javax.swing.JButton btnStaffIncomeReport;
    private javax.swing.JButton btnStaffReports;
    private javax.swing.JButton btnStaffViewBookings;
    private javax.swing.JButton btnStaffViewCustomers;
    private javax.swing.JButton btnStaffViewRooms;
    private javax.swing.JButton btnStaffViewStaff;
    private javax.swing.JButton btnSubmitPassword;
    private javax.swing.JButton btnTrunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jdateDateFrom;
    private com.toedter.calendar.JDateChooser jdateDateUntil;
    private javax.swing.JFrame jframeEditStaffDetails;
    private javax.swing.JFrame jframeStaffChangePassword;
    private javax.swing.JFrame jframeStaffReports;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmailStaff;
    private javax.swing.JTextField txtFirstNameStaff;
    private javax.swing.JTextField txtLastNameStaff;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsernameStaff;
    // End of variables declaration//GEN-END:variables
}
